//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFitApp.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int id_Monitor { get; set; }
        public Nullable<decimal> precioHora { get; set; }
        public System.DateTime fechaAlta { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
