//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFitApp.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int id_Persona { get; set; }
        public string email { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string direccion { get; set; }
        public Nullable<int> codigoPostal { get; set; }
        public string provincia { get; set; }
        public string dniNifNie { get; set; }
        public string password { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Monitor Monitor { get; set; }
    }
}
